---
- name: Install and start the apche
  hosts: all 
  become: yes

  tasks: 
  - name: start the servive
    service:
        name=httpd
        state=stopped

  - name: Install the apache 
    yum: 
      name=httpd
      state=absent
